name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - name: SSH into the server
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
          ssh -i ~/ssh_key ubuntu@16.171.133.86
          cd monorepo && git pull 
          pnpm i
          npx turbo run build --filter=http-server
          npx turbo run build --filter=ws-server
          npx turbo run build
          pm2 restart http-server
          pm2 restart ws-server
          pm2 restart fe
