name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export PATH=/home/ubuntu/.nvm/versions/node/v22.14.0/bin:$PATH
            cd /home/ubuntu/monorepo
            git pull
            pnpm i
            npx turbo run build --filter=http-server
            npx turbo run build --filter=ws-server
            npx turbo run build
            pm2 restart http-server
            pm2  restart ws-server
            pm2 restart fe
